### ISSUE TITLE
subscribe_on_new_system crash

### ISSUE THREAD

**Issue by bh-tneukom** [fada-catec/piloting-mavsdk#1]
```
return std::any_of(systems().cbegin(), systems().cend(), [](auto& system) {
    return system->is_connected();
});
```

This calls systems() twice both time returning a new std::vector and therefore cbegin() and cend() are iterators from two different containers, crashing in VC++ debug mode. I temporarily replaced it by:

```
auto systems_ = systems();
return std::any_of(systems_ .cbegin(), systems_ .cend(), [](auto& system) {
    return system->is_connected();
});
```

**Comment by rcabg** [comment]
Hey @bh-tneukom , thanks for pointing that out. I've just modified it in the repository. Hope it is fine now.
